project:
  type: website
  output-dir: docs
#  pre-render:
    # - scripts/pre_create_papers_file.py
    # - scripts/pre_check_skierg_records.py
    # - scripts/pre_doi_from_rogue_scholar.py
    # - scripts/pre_canonicalise_tags.py

website:
  title: "R Code Stories"
  description: "J. Andrés Delgado-Ron is a social epidemiologist working with data at Simon Fraser University. These are his stoRies"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Creating_the_BC_schools_Master_File.html
        text: Story 1
  page-footer:
    left: "(copyleft) Jorge Andrés Delgado-Ron, 2024. [Disclaimer](disclaimer)"
  twitter-card: false
  open-graph: true


format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: true
    toc_depth: 3
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true
    fig-align: center
    include-in-header:
      text: |
        <script type='application/ld+json'>{"@context":"http://www.schema.org","@type":"person","name":"Jorge Andrés Delgado-Ron","jobTitle":"Data Analyst","height":"175 cm","gender":"male","description":"J. Andrés Delgado-Ron is a public health researcher and social epidemiologist.","url":"https://jorgeandr3s.github.io/r-code-stories/","image":"https://jorgeandr3s.github.io/r-code-stories/img/jandres.jpg","address":{"@type":"PostalAddress","addressLocality":"Ottawa","addressRegion":"ON","postalCode":"K1N5G2","addressCountry":"Canada"},"alumniOf":[{"@type":"CollegeOrUniversity","name":"University of British Columbia","sameAs":"https://en.wikipedia.org/wiki/University_of_British_Columbia"}],"worksFor":[{"@type":"Organization","name":"Simon Fraser University"}],"birthDate":"1986-07-02","birthPlace":"Quito, Ecuador","nationality":[{"@type":"Country","name":"Ecuador"},{"@type":"Country","name":"Canada (PR)"}]}</script>

